/* ============================================================
   §39 DIE ZUKUNFT — the interface as language.

   KAI opens to near-black and ONE sentence. Not a dashboard reduced to a
   headline; the answer to "what is happening in my life", said as prose.

   ── WHY THIS FILE IS DETERMINISTIC ────────────────────────────
   The opening sentence is the most trusted text in the whole app: it is
   the only thing on screen, it is read before anything else, and it will
   be believed. So it is NOT generated by a model. Every sentence here is
   a template with a PREDICATE over the Spine, and the predicate has to
   hold before the words can be said.

   The brief's own example — "Hatem checks out tomorrow. The cleaner
   doesn't know yet." — is two claims of very different kinds. The first
   is a fact in the record. The second is an ABSENCE, and an absence is
   only knowable if you have looked: the second clause is appended only
   when the Spine shows no outbound message about that stay. Where it
   cannot be checked, the sentence stops after the first clause rather
   than guessing at the second.

   That is the whole discipline of this file. A quiet life gets a quiet
   sentence. Nothing is dramatised to fill the screen.
   ============================================================ */

import { getEvents, type KaiEvent } from './events';
import { type CouncilContext } from './council';

const DAY = 86_400_000;
const HOUR = 3_600_000;

/* ── the moment ───────────────────────────────────────────────
   The interface is never the same twice because the moment never is. */

export type Hour = 'dawn' | 'day' | 'dusk' | 'night';
export type Cadence = 'ahead' | 'now' | 'record' | 'verdict';

export interface Moment { hour: Hour; cadence: Cadence; sunday: boolean; label: string }

export function moment(now = Date.now()): Moment {
  const d = new Date(now);
  const h = d.getHours();
  const sunday = d.getDay() === 0;
  const hour: Hour = h < 4 ? 'night' : h < 11 ? 'dawn' : h < 17 ? 'day' : h < 22 ? 'dusk' : 'night';
  /* Sunday evening is the week's verdict; the week is over and reading it
     is the only useful thing left to do with it. */
  const cadence: Cadence = sunday && (hour === 'dusk' || hour === 'night') ? 'verdict'
    : hour === 'dawn' ? 'ahead'
    : hour === 'night' ? 'record'
    : 'now';
  const label = cadence === 'ahead' ? 'the day ahead'
    : cadence === 'record' ? "the day's record"
    : cadence === 'verdict' ? "the week's verdict"
    : 'right now';
  return { hour, cadence, sunday, label };
}

/* ── the sentence ─────────────────────────────────────────────── */

export interface Sentence {
  text: string;
  /* Always available behind the sentence — a first screen with one claim
     on it must be able to show its working on demand. */
  because: string;
  evidence: string[];
  weight: number;          // consequence, for choosing between candidates
  source: string;
}

function fmt(n: number): string { return Math.round(n).toLocaleString('en-GB'); }
function ids(evs: KaiEvent[], n = 4): string[] { return evs.slice(-n).map((e) => e.id); }

/* Did anything go OUT about this guest/stay since it was recorded? An
   absence is only reportable once you have actually looked for presence. */
function saidAnythingAbout(guest: string, since: number, now: number): boolean {
  if (!guest) return true;                 // cannot check → never claim silence
  const g = guest.toLowerCase();
  return getEvents({ since })
    .filter((e) => e.ts <= now)
    .some((e) => {
      if (!/email_sent|sms_sent|message_sent|booking_replied|reel_posted/.test(e.type)) return false;
      const blob = JSON.stringify(e.meta || {}).toLowerCase();
      return blob.includes(g) || /clean|turnover|housekeep/.test(blob);
    });
}

type Candidate = (ctx: CouncilContext, now: number) => Sentence | null;

/* 1. A CHECKOUT TOMORROW — the brief's own example, built honestly. */
const checkout: Candidate = (_ctx, now) => {
  const bookings = getEvents({ domain: 'makadi', type: 'booking_confirmed' });
  for (const b of bookings) {
    const outRaw = b.meta?.checkout ?? b.meta?.endsAt ?? b.meta?.until;
    const out = typeof outRaw === 'number' ? outRaw : Date.parse(String(outRaw ?? ''));
    if (!isFinite(out)) continue;
    const days = Math.round((out - now) / DAY);
    if (days < 0 || days > 1) continue;
    const guest = String(b.meta?.guest || '').trim();
    const who = guest || 'Your guest';
    const when = days === 0 ? 'today' : 'tomorrow';

    /* The second clause exists ONLY if the silence is provable. */
    const told = saidAnythingAbout(guest, b.ts, now);
    const text = told
      ? `${who} checks out ${when}.`
      : `${who} checks out ${when}. The cleaner doesn't know yet.`;
    return {
      text,
      because: told
        ? `Booking on record with a checkout date ${when}.`
        : `Booking on record with a checkout date ${when}, and nothing has gone out about the turnover since it was booked.`,
      evidence: [b.id], weight: 900 - days, source: 'makadi',
    };
  }
  return null;
};

/* 2. AN INQUIRY GOING COLD — money walking away while he reads. */
const inquiry: Candidate = (ctx, now) => {
  const open = ctx.openInquiries || [];
  if (!open.length) return null;
  const oldest = open.reduce((a, b) => (a.ts < b.ts ? a : b));
  const hours = Math.floor((now - oldest.ts) / HOUR);
  if (hours < 2) return null;
  const guest = String(oldest.meta?.guest || '').trim();
  const who = guest ? guest : 'Someone';
  const age = hours < 24 ? `${hours} hours` : `${Math.floor(hours / 24)} days`;
  return {
    text: `${who} asked about the flat ${age} ago and is still waiting.`,
    because: `A booking inquiry on record with no reply and no booking against it.`,
    evidence: [oldest.id], weight: 950 + Math.min(hours, 200), source: 'makadi',
  };
};

/* 3. A PROMISE PAST ITS DATE. */
const overdue: Candidate = (ctx, now) => {
  const list = ctx.overdue || [];
  if (!list.length) return null;
  const worst = list.reduce((a, b) => (a.deadline < b.deadline ? a : b));
  const days = Math.max(1, Math.floor((now - worst.deadline) / DAY));
  return {
    text: list.length === 1
      ? `"${worst.text}" was due ${days} ${days === 1 ? 'day' : 'days'} ago.`
      : `${list.length} things are past their date. The oldest is "${worst.text}", ${days} days over.`,
    because: 'Commitments you set, with dates that have passed.',
    evidence: [worst.id], weight: 800 + Math.min(days * 4, 160), source: 'commitment',
  };
};

/* 4. THE WALLS GETTING CLOSER. */
const runway: Candidate = (ctx) => {
  const r = ctx.runway;
  if (!r || r.runwayDays === null || r.sampleCount < 8) return null;
  const d = Math.floor(r.runwayDays);
  if (d > 45) return null;
  return {
    text: d <= 14
      ? `You have ${d} days of money left at the rate you're spending.`
      : `${d} days of runway. That's the number that decides the month.`,
    because: `${fmt(r.liquidCash)} EGP liquid against ${fmt(r.dailyBurn)} EGP a day, from ${r.sampleCount} logged expenses.`,
    evidence: [], weight: d <= 14 ? 990 : 700, source: 'runway',
  };
};

/* 5. A DATE THAT DOES NOT MOVE. */
const legal: Candidate = (_ctx, now) => {
  const deadlines = (() => {
    try { return JSON.parse(localStorage.getItem('kai.deadlines') || '[]') as Array<{ text: string; date: number }>; }
    catch { return []; }
  })();
  const next = deadlines.filter((d) => d.date > now).sort((a, b) => a.date - b.date)[0];
  if (!next) return null;
  const days = Math.ceil((next.date - now) / DAY);
  if (days > 30) return null;
  return {
    text: days <= 1 ? `${next.text} — tomorrow.` : `${next.text} in ${days} days.`,
    because: 'A hard date you set. It does not move.',
    evidence: [], weight: 850 + Math.max(0, 30 - days) * 3, source: 'deadline',
  };
};

/* 6. SOMETHING GOOD, WHICH ALSO COUNTS. */
const good: Candidate = (_ctx, now) => {
  const recent = getEvents({ domain: 'makadi', type: 'booking_confirmed', since: now - 2 * DAY });
  if (!recent.length) return null;
  const b = recent[recent.length - 1];
  const guest = String(b.meta?.guest || 'Someone').trim();
  const nights = Number(b.meta?.nights) || 0;
  return {
    text: nights ? `${guest} booked ${nights} night${nights === 1 ? '' : 's'}.` : `${guest} booked.`,
    because: 'A confirmed booking in the last two days.',
    evidence: [b.id], weight: 600, source: 'makadi',
  };
};

/* 7. THE QUIET ONE. Not a filler — the honest answer when the record
      holds nothing that needs him. It says so plainly. */
function quiet(ctx: CouncilContext, now: number): Sentence {
  const m = moment(now);
  const p = ctx.profit;
  if (m.cadence === 'verdict') {
    return {
      text: 'The week is done. Nothing is on fire.',
      because: 'No open inquiry, no overdue commitment, no short runway on the record.',
      evidence: [], weight: 0, source: 'quiet',
    };
  }
  if (p && p.nightsBooked > 0) {
    return {
      text: `${p.nightsBooked} nights on the books. Nothing needs you today.`,
      because: 'Read from your own bookings. No demand anywhere in the record.',
      evidence: [], weight: 0, source: 'quiet',
    };
  }
  return {
    text: 'Nothing needs you right now.',
    because: 'The record holds no open demand. That is the finding, not a greeting.',
    evidence: [], weight: 0, source: 'quiet',
  };
}

const CANDIDATES: Candidate[] = [inquiry, runway, checkout, legal, overdue, good];

export function theSentence(ctx: CouncilContext, now = Date.now()): Sentence {
  const found = CANDIDATES
    .map((c) => { try { return c(ctx, now); } catch { return null; } })
    .filter((s): s is Sentence => s !== null)
    .sort((a, b) => b.weight - a.weight);
  return found[0] ?? quiet(ctx, now);
}

/* The SECOND line, shown smaller and only when a second thing genuinely
   deserves the first screen. Most days there is nothing here. */
export function theSecond(ctx: CouncilContext, now = Date.now()): Sentence | null {
  const found = CANDIDATES
    .map((c) => { try { return c(ctx, now); } catch { return null; } })
    .filter((s): s is Sentence => s !== null)
    .sort((a, b) => b.weight - a.weight);
  const second = found[1];
  /* A second sentence has to clear a real bar, or the screen stops being
     one sentence and becomes a list with extra steps. */
  return second && second.weight >= 800 && second.source !== found[0]?.source ? second : null;
}

/* ── the surface ──────────────────────────────────────────────
   The body IS the chrome. These are the only visual variables in §39:
   a colour, a bloom, a weight, and a tempo. Everything on screen is
   derived from them, so a pressed month looks pressed before a word of
   it is read. */

export interface Mood {
  rgb: string;
  glow: number;
  /* Typographic weight of the sentence — pressure reads as heavier text. */
  weight: 300 | 400 | 600;
  /* Seconds per breath. Slow when calm, quick when hunted. */
  tempo: number;
  /* Background warmth, 0..1 — how far the near-black lifts toward blood. */
  warmth: number;
}

const MOOD: Record<string, Mood> = {
  STEADY:  { rgb: '255,180,110', glow: 0.30, weight: 300, tempo: 6.0, warmth: 0.04 },
  RISING:  { rgb: '255,196,120', glow: 0.46, weight: 400, tempo: 4.6, warmth: 0.07 },
  HUNTING: { rgb: '255,166,80',  glow: 0.52, weight: 400, tempo: 3.6, warmth: 0.09 },
  PRESSED: { rgb: '235,120,70',  glow: 0.60, weight: 600, tempo: 2.8, warmth: 0.13 },
  WOUNDED: { rgb: '208,72,52',   glow: 0.72, weight: 600, tempo: 2.2, warmth: 0.18 },
};

export function moodFor(being: string): Mood { return MOOD[being] ?? MOOD.STEADY; }

/* Night is dimmer everywhere. The interface should not shout at 1am. */
export function dimFor(m: Moment): number {
  return m.hour === 'night' ? 0.72 : m.hour === 'dawn' ? 0.92 : 1;
}
